export const QUEST_DETAILS_COMPONENTS_TYPES = [
  "TITLE_COMP",
  "TEXTBOX_COMP",
  "IMAGE_COMP",
  "QUOTE_COMP",
  "IMAGE_CAROUSEL",
  "ANIMATION",
];

export const QUEST_STEPS_COMPONENTS_TYPES = [
  "TITLE_COMP",
  "TEXTBOX_COMP",
  "IMAGE_COMP",
  "VIDEO_COMP",
  "SOUND_COMP",
  "QUOTE_COMP",
  "INPUT_COMP",
  "SINGLE_PICKER",
  "MULTI_PICKER",
  "IMAGE_CAROUSEL",
  "ANIMATION",
];

export const QUEST_FINISHES_COMPONENTS_TYPES = [
  "TITLE_COMP",
  "TEXTBOX_COMP",
  "IMAGE_COMP",
  "QUOTE_COMP",
  "IMAGE_CAROUSEL",
  "ANIMATION",
];
